version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: new_employee_db
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: backend11
    ports:
      - "3430:3430"
    environment:
      - PORT=3430
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin234
      - DB_NAME=new_employee_db
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./Frontend
    container_name: frontend11
    ports:
      - "8055:80"
    depends_on:
      - backend

  hr_page:
    build: ./Hr_page
    container_name: hr_page11
    ports:
      - "8056:80"
    depends_on:
      - backend

volumes:
  pgdata:
